// <auto-generated />
namespace MVC_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class candle_price : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(candle_price));
        
        string IMigrationMetadata.Id
        {
            get { return "201604030828442_candle_price"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
