// <auto-generated />
namespace MVC_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class candlestore_schema : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(candlestore_schema));
        
        string IMigrationMetadata.Id
        {
            get { return "201604151651517_candlestore_schema"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
